<?php

function hello_init(){
//drupal_set_message("Hii");
}


function hello_menu(){
$items=array();

$items['hellopage']=array(

'title'=>'My Hello Page',
'description'=>'Hello to all',
'page callback'=>'drupal_get_form',
'page arguments'=>array('hello_showHelloForm'),
'acces callback'=>'user_access',
'access arguments'=>array('access content'),
'type'=>MENU_NORMAL_ITEM

);
$items['gethello']=array(
'page callback'=>'hello_ajaxCallHandler',
'acces callback'=>'user_access',
'access arguments'=>array('access content'),
'type'=>MENU_CALLBACK

);
return $items;


}
function hello_ajaxCallHandler(){

//echo "Hello through call back".$_GET['name'];

}
function hello_showHelloForm(){
$form=array();
$form['name']=array(

'#type'=>'textfield',
'#title'=>'Enter your name',


);

$form['submit']=array(
'#type'=>'submit',
'#value'=>'Submit'
);

$form['#submit'][]='hello_showHelloForm_submit';
$form['#suffix']='<input type="button" id="submitAjaxButton" value="Submit with Ajax">
<div id="msg-display-area"></div>';

drupal_add_js(drupal_get_path('module','hello')."/hello.js");
return $form;

}

function hello_showHelloForm_submit($form,&$form_state){
if($form_state['values']['name'] == ""){
form_set_error('name','Name cannot be empty');
}else{
drupal_set_message("hello ".$form_state['values']['name']."  !");
}
}